# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\YandexDisk\Документы\Python Scripts\NDM_python\designer\formBetonsEditor.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormBetonEditor(object):
    def setupUi(self, FormBetonEditor):
        FormBetonEditor.setObjectName("FormBetonEditor")
        FormBetonEditor.resize(335, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FormBetonEditor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(FormBetonEditor)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBoxNum = QtWidgets.QSpinBox(FormBetonEditor)
        self.spinBoxNum.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxNum.setMinimum(1)
        self.spinBoxNum.setObjectName("spinBoxNum")
        self.horizontalLayout.addWidget(self.spinBoxNum)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(FormBetonEditor)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBoxClass = QtWidgets.QComboBox(FormBetonEditor)
        self.comboBoxClass.setObjectName("comboBoxClassB")
        self.horizontalLayout_2.addWidget(self.comboBoxClass)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(FormBetonEditor)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBoxDiagr = QtWidgets.QComboBox(FormBetonEditor)
        self.comboBoxDiagr.setObjectName("comboBoxDiagr")
        self.horizontalLayout_3.addWidget(self.comboBoxDiagr)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(FormBetonEditor)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBoxVlag = QtWidgets.QComboBox(FormBetonEditor)
        self.comboBoxVlag.setObjectName("comboBoxVlag")
        self.horizontalLayout_4.addWidget(self.comboBoxVlag)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(FormBetonEditor)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBoxGamma_b3 = QtWidgets.QComboBox(FormBetonEditor)
        self.comboBoxGamma_b3.setObjectName("comboBoxGamma_b3")
        self.horizontalLayout_5.addWidget(self.comboBoxGamma_b3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_6 = QtWidgets.QLabel(FormBetonEditor)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.plainTextEditDescript = QtWidgets.QPlainTextEdit(FormBetonEditor)
        self.plainTextEditDescript.setObjectName("plainTextEditDescript")
        self.verticalLayout.addWidget(self.plainTextEditDescript)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonDel = QtWidgets.QPushButton(FormBetonEditor)
        self.pushButtonDel.setObjectName("pushButtonDel")
        self.horizontalLayout_6.addWidget(self.pushButtonDel)
        self.comboBoxNums = QtWidgets.QComboBox(FormBetonEditor)
        self.comboBoxNums.setObjectName("comboBoxNums")
        self.horizontalLayout_6.addWidget(self.comboBoxNums)
        self.pushButtonEdit = QtWidgets.QPushButton(FormBetonEditor)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.horizontalLayout_6.addWidget(self.pushButtonEdit)
        self.pushButtonAdd = QtWidgets.QPushButton(FormBetonEditor)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout_6.addWidget(self.pushButtonAdd)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(FormBetonEditor)
        QtCore.QMetaObject.connectSlotsByName(FormBetonEditor)

    def retranslateUi(self, FormBetonEditor):
        _translate = QtCore.QCoreApplication.translate
        FormBetonEditor.setWindowTitle(_translate("FormBetonEditor", "Редактор бетона"))
        self.label.setText(_translate("FormBetonEditor", "Номер:"))
        self.label_2.setText(_translate("FormBetonEditor", "Класс:"))
        self.label_3.setText(_translate("FormBetonEditor", "Диаграмма деформирования:"))
        self.label_4.setText(_translate("FormBetonEditor", "Влажность среды:"))
        self.label_5.setText(_translate("FormBetonEditor", "Коэффициент γb3:"))
        self.label_6.setText(_translate("FormBetonEditor", "Описание:"))
        self.pushButtonDel.setText(_translate("FormBetonEditor", "Удалить"))
        self.pushButtonEdit.setText(_translate("FormBetonEditor", "Изменить"))
        self.pushButtonAdd.setText(_translate("FormBetonEditor", "Создать"))
