# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\YandexDisk\Документы\Python Scripts\NDM_python\designer\formEffLengthElems.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormEffLengthElems(object):
    def setupUi(self, FormEffLengthElems):
        FormEffLengthElems.setObjectName("FormEffLengthElems")
        FormEffLengthElems.resize(470, 415)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FormEffLengthElems)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton1 = QtWidgets.QRadioButton(FormEffLengthElems)
        self.radioButton1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton1.setAutoFillBackground(False)
        self.radioButton1.setChecked(True)
        self.radioButton1.setObjectName("radioButton1")
        self.verticalLayout.addWidget(self.radioButton1)
        self.line = QtWidgets.QFrame(FormEffLengthElems)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.radioButton2_1 = QtWidgets.QRadioButton(FormEffLengthElems)
        self.radioButton2_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton2_1.setObjectName("radioButton2_1")
        self.verticalLayout.addWidget(self.radioButton2_1)
        self.line_2 = QtWidgets.QFrame(FormEffLengthElems)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label = QtWidgets.QLabel(FormEffLengthElems)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setIndent(20)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.radioButton0_7 = QtWidgets.QRadioButton(FormEffLengthElems)
        self.radioButton0_7.setObjectName("radioButton0_7")
        self.verticalLayout.addWidget(self.radioButton0_7)
        self.radioButton0_9 = QtWidgets.QRadioButton(FormEffLengthElems)
        self.radioButton0_9.setObjectName("radioButton0_9")
        self.verticalLayout.addWidget(self.radioButton0_9)
        self.line_3 = QtWidgets.QFrame(FormEffLengthElems)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_2 = QtWidgets.QLabel(FormEffLengthElems)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setIndent(20)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.radioButton1_5 = QtWidgets.QRadioButton(FormEffLengthElems)
        self.radioButton1_5.setObjectName("radioButton1_5")
        self.verticalLayout.addWidget(self.radioButton1_5)
        self.radioButton2_2 = QtWidgets.QRadioButton(FormEffLengthElems)
        self.radioButton2_2.setObjectName("radioButton2_2")
        self.verticalLayout.addWidget(self.radioButton2_2)
        self.line_5 = QtWidgets.QFrame(FormEffLengthElems)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.label_3 = QtWidgets.QLabel(FormEffLengthElems)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setIndent(20)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.radioButton0_5 = QtWidgets.QRadioButton(FormEffLengthElems)
        self.radioButton0_5.setObjectName("radioButton0_5")
        self.verticalLayout.addWidget(self.radioButton0_5)
        self.radioButton0_8_1 = QtWidgets.QRadioButton(FormEffLengthElems)
        self.radioButton0_8_1.setObjectName("radioButton0_8_1")
        self.verticalLayout.addWidget(self.radioButton0_8_1)
        self.line_4 = QtWidgets.QFrame(FormEffLengthElems)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_4 = QtWidgets.QLabel(FormEffLengthElems)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setIndent(20)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.radioButton0_8_2 = QtWidgets.QRadioButton(FormEffLengthElems)
        self.radioButton0_8_2.setObjectName("radioButton0_8_2")
        self.verticalLayout.addWidget(self.radioButton0_8_2)
        self.radioButton1_2 = QtWidgets.QRadioButton(FormEffLengthElems)
        self.radioButton1_2.setObjectName("radioButton1_2")
        self.verticalLayout.addWidget(self.radioButton1_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(FormEffLengthElems)
        QtCore.QMetaObject.connectSlotsByName(FormEffLengthElems)

    def retranslateUi(self, FormEffLengthElems):
        _translate = QtCore.QCoreApplication.translate
        FormEffLengthElems.setWindowTitle(_translate("FormEffLengthElems", "Коэффициенты расчетных длин"))
        self.radioButton1.setText(_translate("FormEffLengthElems", "Для элементов с шарнирным опиранием на двух концах - 1.0"))
        self.radioButton2_1.setText(_translate("FormEffLengthElems", "Для элементов с жесткой заделкой (исключающей поворот\n"
"опорного сечения) на одном конце и незакрепленным другим концом\n"
"(консоль) - 2.0"))
        self.label.setText(_translate("FormEffLengthElems", "Для элементов с шарнирным несмещаемым опиранием на одном конце, а на другом конце:"))
        self.radioButton0_7.setText(_translate("FormEffLengthElems", "с жесткой (без поворота) заделкой - 0.7"))
        self.radioButton0_9.setText(_translate("FormEffLengthElems", "с податливой (допускающей ограниченный поворот) заделкой - 0.9"))
        self.label_2.setText(_translate("FormEffLengthElems", "Для элементов с податливым шарнирным опиранием (допускающем ограниченное смещение опоры) на одном конце, а на другом конце:"))
        self.radioButton1_5.setText(_translate("FormEffLengthElems", "с жесткой (без поворота) заделкой - 1.5"))
        self.radioButton2_2.setText(_translate("FormEffLengthElems", "податливой (с ограниченным поворотом) заделкой - 2.0"))
        self.label_3.setText(_translate("FormEffLengthElems", "Для элементов с несмещаемыми заделками на двух концах:"))
        self.radioButton0_5.setText(_translate("FormEffLengthElems", "жесткими (без поворота) - 0.5"))
        self.radioButton0_8_1.setText(_translate("FormEffLengthElems", "податливыми (с ограниченным поворотом) - 0.8"))
        self.label_4.setText(_translate("FormEffLengthElems", "Для элементов с ограниченно смещаемыми заделками на двух концах:"))
        self.radioButton0_8_2.setText(_translate("FormEffLengthElems", "жесткими (без поворота) - 0.8"))
        self.radioButton1_2.setText(_translate("FormEffLengthElems", "податливыми (с ограниченным поворотом) - 1.2"))
