# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\YandexDisk\Документы\Python Scripts\NDM_python\designer\formElementsEditor.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormElementsEditor(object):
    def setupUi(self, FormElementsEditor):
        FormElementsEditor.setObjectName("FormElementsEditor")
        FormElementsEditor.resize(360, 511)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(FormElementsEditor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelNumGroup = QtWidgets.QLabel(FormElementsEditor)
        self.labelNumGroup.setObjectName("labelNumGroup")
        self.horizontalLayout_4.addWidget(self.labelNumGroup)
        self.spinBoxNumElement = QtWidgets.QSpinBox(FormElementsEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxNumElement.sizePolicy().hasHeightForWidth())
        self.spinBoxNumElement.setSizePolicy(sizePolicy)
        self.spinBoxNumElement.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBoxNumElement.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxNumElement.setMaximum(9999)
        self.spinBoxNumElement.setObjectName("spinBoxNumElement")
        self.horizontalLayout_4.addWidget(self.spinBoxNumElement)
        self.pushButtonAddElement = QtWidgets.QPushButton(FormElementsEditor)
        self.pushButtonAddElement.setObjectName("pushButtonAddElement")
        self.horizontalLayout_4.addWidget(self.pushButtonAddElement)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(FormElementsEditor)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.chbDefShema = QtWidgets.QCheckBox(FormElementsEditor)
        self.chbDefShema.setObjectName("chbDefShema")
        self.verticalLayout.addWidget(self.chbDefShema)
        self.label_2 = QtWidgets.QLabel(FormElementsEditor)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(FormElementsEditor)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.doubleSpinBoxL0x = QtWidgets.QDoubleSpinBox(FormElementsEditor)
        self.doubleSpinBoxL0x.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxL0x.setDecimals(1)
        self.doubleSpinBoxL0x.setMaximum(2.0)
        self.doubleSpinBoxL0x.setSingleStep(0.1)
        self.doubleSpinBoxL0x.setProperty("value", 1.0)
        self.doubleSpinBoxL0x.setObjectName("doubleSpinBoxL0x")
        self.horizontalLayout_2.addWidget(self.doubleSpinBoxL0x)
        self.toolButtonLox = QtWidgets.QToolButton(FormElementsEditor)
        self.toolButtonLox.setObjectName("toolButtonLox")
        self.horizontalLayout_2.addWidget(self.toolButtonLox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(FormElementsEditor)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.doubleSpinBoxL0y = QtWidgets.QDoubleSpinBox(FormElementsEditor)
        self.doubleSpinBoxL0y.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxL0y.setDecimals(1)
        self.doubleSpinBoxL0y.setMaximum(2.0)
        self.doubleSpinBoxL0y.setSingleStep(0.1)
        self.doubleSpinBoxL0y.setProperty("value", 1.0)
        self.doubleSpinBoxL0y.setObjectName("doubleSpinBoxL0y")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxL0y)
        self.toolButtonLoy = QtWidgets.QToolButton(FormElementsEditor)
        self.toolButtonLoy.setObjectName("toolButtonLoy")
        self.horizontalLayout_3.addWidget(self.toolButtonLoy)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(FormElementsEditor)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label = QtWidgets.QLabel(FormElementsEditor)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.checkBoxStatOprMx = QtWidgets.QCheckBox(FormElementsEditor)
        self.checkBoxStatOprMx.setObjectName("checkBoxStatOprMx")
        self.verticalLayout.addWidget(self.checkBoxStatOprMx)
        self.checkBoxStatOprMy = QtWidgets.QCheckBox(FormElementsEditor)
        self.checkBoxStatOprMy.setObjectName("checkBoxStatOprMy")
        self.verticalLayout.addWidget(self.checkBoxStatOprMy)
        self.line_3 = QtWidgets.QFrame(FormElementsEditor)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbNumsFes = QtWidgets.QComboBox(FormElementsEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbNumsFes.sizePolicy().hasHeightForWidth())
        self.cbNumsFes.setSizePolicy(sizePolicy)
        self.cbNumsFes.setObjectName("cbNumsFes")
        self.horizontalLayout_5.addWidget(self.cbNumsFes)
        self.pushButtonAddFe = QtWidgets.QPushButton(FormElementsEditor)
        self.pushButtonAddFe.setObjectName("pushButtonAddFe")
        self.horizontalLayout_5.addWidget(self.pushButtonAddFe)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tableView = QtWidgets.QTableView(FormElementsEditor)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.pushButtonDelFe = QtWidgets.QPushButton(FormElementsEditor)
        self.pushButtonDelFe.setObjectName("pushButtonDelFe")
        self.verticalLayout.addWidget(self.pushButtonDelFe)
        self.line_4 = QtWidgets.QFrame(FormElementsEditor)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_5 = QtWidgets.QLabel(FormElementsEditor)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(FormElementsEditor)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.doubleSpinBoxEax = QtWidgets.QDoubleSpinBox(FormElementsEditor)
        self.doubleSpinBoxEax.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxEax.setSingleStep(0.1)
        self.doubleSpinBoxEax.setObjectName("doubleSpinBoxEax")
        self.horizontalLayout_6.addWidget(self.doubleSpinBoxEax)
        self.toolButton = QtWidgets.QToolButton(FormElementsEditor)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_6.addWidget(self.toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(FormElementsEditor)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.doubleSpinBoxEay = QtWidgets.QDoubleSpinBox(FormElementsEditor)
        self.doubleSpinBoxEay.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxEay.setSingleStep(0.1)
        self.doubleSpinBoxEay.setObjectName("doubleSpinBoxEay")
        self.horizontalLayout_7.addWidget(self.doubleSpinBoxEay)
        self.toolButton_2 = QtWidgets.QToolButton(FormElementsEditor)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_7.addWidget(self.toolButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(FormElementsEditor)
        QtCore.QMetaObject.connectSlotsByName(FormElementsEditor)

    def retranslateUi(self, FormElementsEditor):
        _translate = QtCore.QCoreApplication.translate
        FormElementsEditor.setWindowTitle(_translate("FormElementsEditor", "Редактор элементов"))
        self.labelNumGroup.setText(_translate("FormElementsEditor", "Номер элемента:"))
        self.pushButtonAddElement.setText(_translate("FormElementsEditor", "Добавить элемент"))
        self.chbDefShema.setText(_translate("FormElementsEditor", "Учитывать влияние прогиба и случайного эксценнтриситета"))
        self.label_2.setText(_translate("FormElementsEditor", "Коэффициенты расчетной длины:"))
        self.label_3.setText(_translate("FormElementsEditor", "в плоскости действия момента Mx, l0x"))
        self.toolButtonLox.setText(_translate("FormElementsEditor", "..."))
        self.label_4.setText(_translate("FormElementsEditor", "в плоскости действия момента My, l0y"))
        self.toolButtonLoy.setText(_translate("FormElementsEditor", "..."))
        self.label.setText(_translate("FormElementsEditor", "Элемент статически определимой конструкции:"))
        self.checkBoxStatOprMx.setText(_translate("FormElementsEditor", " в плоскости действия момента Mx"))
        self.checkBoxStatOprMy.setText(_translate("FormElementsEditor", "в плоскости действия момента My"))
        self.pushButtonAddFe.setText(_translate("FormElementsEditor", "Добавить участок"))
        self.pushButtonDelFe.setText(_translate("FormElementsEditor", "Удалить участок"))
        self.label_5.setText(_translate("FormElementsEditor", "Случайные эксцентриситеты:"))
        self.label_6.setText(_translate("FormElementsEditor", "в плоскости действия момента Mx, eax, cм"))
        self.toolButton.setText(_translate("FormElementsEditor", "..."))
        self.label_7.setText(_translate("FormElementsEditor", "в плоскости действия момента My, eay, cм"))
        self.toolButton_2.setText(_translate("FormElementsEditor", "..."))
