# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\palex\YandexDisk\Документы\Python Scripts\NDM_python\designer\formLoadsEditor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormLoadsCreator(object):
    def setupUi(self, FormLoadsCreator):
        FormLoadsCreator.setObjectName("FormLoadsCreator")
        FormLoadsCreator.resize(633, 435)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FormLoadsCreator)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelNumGroup = QtWidgets.QLabel(FormLoadsCreator)
        self.labelNumGroup.setObjectName("labelNumGroup")
        self.horizontalLayout_4.addWidget(self.labelNumGroup)
        self.spinBoxNumGroup = QtWidgets.QSpinBox(FormLoadsCreator)
        self.spinBoxNumGroup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBoxNumGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxNumGroup.setMaximum(9999)
        self.spinBoxNumGroup.setObjectName("spinBoxNumGroup")
        self.horizontalLayout_4.addWidget(self.spinBoxNumGroup)
        self.pushButtonAddLoadsGroup = QtWidgets.QPushButton(FormLoadsCreator)
        self.pushButtonAddLoadsGroup.setObjectName("pushButtonAddLoadsGroup")
        self.horizontalLayout_4.addWidget(self.pushButtonAddLoadsGroup)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(FormLoadsCreator)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(FormLoadsCreator)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBoxLoadsType = QtWidgets.QComboBox(FormLoadsCreator)
        self.comboBoxLoadsType.setObjectName("comboBoxLoadsType")
        self.comboBoxLoadsType.addItem("")
        self.comboBoxLoadsType.addItem("")
        self.comboBoxLoadsType.addItem("")
        self.comboBoxLoadsType.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBoxLoadsType)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(FormLoadsCreator)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.doubleSpinBoxKdl = QtWidgets.QDoubleSpinBox(FormLoadsCreator)
        self.doubleSpinBoxKdl.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxKdl.setSingleStep(0.01)
        self.doubleSpinBoxKdl.setProperty("value", 0.9)
        self.doubleSpinBoxKdl.setObjectName("doubleSpinBoxKdl")
        self.horizontalLayout_6.addWidget(self.doubleSpinBoxKdl)
        self.label_4 = QtWidgets.QLabel(FormLoadsCreator)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.doubleSpinBoxKd = QtWidgets.QDoubleSpinBox(FormLoadsCreator)
        self.doubleSpinBoxKd.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxKd.setMaximum(2.0)
        self.doubleSpinBoxKd.setSingleStep(0.01)
        self.doubleSpinBoxKd.setProperty("value", 1.0)
        self.doubleSpinBoxKd.setObjectName("doubleSpinBoxKd")
        self.horizontalLayout_6.addWidget(self.doubleSpinBoxKd)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.line_2 = QtWidgets.QFrame(FormLoadsCreator)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(FormLoadsCreator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.doubleSpinBoxN = QtWidgets.QDoubleSpinBox(FormLoadsCreator)
        self.doubleSpinBoxN.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxN.setMaximum(99999.99)
        self.doubleSpinBoxN.setSingleStep(0.1)
        self.doubleSpinBoxN.setObjectName("doubleSpinBoxN")
        self.horizontalLayout.addWidget(self.doubleSpinBoxN)
        self.label_2 = QtWidgets.QLabel(FormLoadsCreator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.doubleSpinBoxMx = QtWidgets.QDoubleSpinBox(FormLoadsCreator)
        self.doubleSpinBoxMx.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxMx.setMaximum(9999.99)
        self.doubleSpinBoxMx.setSingleStep(0.1)
        self.doubleSpinBoxMx.setObjectName("doubleSpinBoxMx")
        self.horizontalLayout.addWidget(self.doubleSpinBoxMx)
        self.label = QtWidgets.QLabel(FormLoadsCreator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.doubleSpinBoxMy = QtWidgets.QDoubleSpinBox(FormLoadsCreator)
        self.doubleSpinBoxMy.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxMy.setMaximum(9999.99)
        self.doubleSpinBoxMy.setSingleStep(0.1)
        self.doubleSpinBoxMy.setObjectName("doubleSpinBoxMy")
        self.horizontalLayout.addWidget(self.doubleSpinBoxMy)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_3 = QtWidgets.QFrame(FormLoadsCreator)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.pushButtonAddLoad = QtWidgets.QPushButton(FormLoadsCreator)
        self.pushButtonAddLoad.setObjectName("pushButtonAddLoad")
        self.verticalLayout.addWidget(self.pushButtonAddLoad)
        self.tableViewLoads = QtWidgets.QTableView(FormLoadsCreator)
        self.tableViewLoads.setObjectName("tableViewLoads")
        self.verticalLayout.addWidget(self.tableViewLoads)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonEditLoad = QtWidgets.QPushButton(FormLoadsCreator)
        self.pushButtonEditLoad.setObjectName("pushButtonEditLoad")
        self.horizontalLayout_5.addWidget(self.pushButtonEditLoad)
        self.pushButtonDelLoad = QtWidgets.QPushButton(FormLoadsCreator)
        self.pushButtonDelLoad.setObjectName("pushButtonDelLoad")
        self.horizontalLayout_5.addWidget(self.pushButtonDelLoad)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_5 = QtWidgets.QFrame(FormLoadsCreator)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(FormLoadsCreator)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.comboBoxTypeConversion = QtWidgets.QComboBox(FormLoadsCreator)
        self.comboBoxTypeConversion.setObjectName("comboBoxTypeConversion")
        self.comboBoxTypeConversion.addItem("")
        self.comboBoxTypeConversion.addItem("")
        self.comboBoxTypeConversion.addItem("")
        self.comboBoxTypeConversion.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBoxTypeConversion)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line_4 = QtWidgets.QFrame(FormLoadsCreator)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbNumsLoadsGroups = QtWidgets.QComboBox(FormLoadsCreator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbNumsLoadsGroups.sizePolicy().hasHeightForWidth())
        self.cbNumsLoadsGroups.setSizePolicy(sizePolicy)
        self.cbNumsLoadsGroups.setObjectName("cbNumsLoadsGroups")
        self.horizontalLayout_2.addWidget(self.cbNumsLoadsGroups)
        self.pushButtonDelLodsGroup = QtWidgets.QPushButton(FormLoadsCreator)
        self.pushButtonDelLodsGroup.setObjectName("pushButtonDelLodsGroup")
        self.horizontalLayout_2.addWidget(self.pushButtonDelLodsGroup)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(FormLoadsCreator)
        self.comboBoxTypeConversion.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormLoadsCreator)

    def retranslateUi(self, FormLoadsCreator):
        _translate = QtCore.QCoreApplication.translate
        FormLoadsCreator.setWindowTitle(_translate("FormLoadsCreator", "Редактор усилий"))
        self.labelNumGroup.setText(_translate("FormLoadsCreator", "Номер группы усилий:"))
        self.pushButtonAddLoadsGroup.setText(_translate("FormLoadsCreator", "Добавить группу"))
        self.label_5.setText(_translate("FormLoadsCreator", "Тип нагрузки и длительность:"))
        self.comboBoxLoadsType.setItemText(0, _translate("FormLoadsCreator", "Расчетные"))
        self.comboBoxLoadsType.setItemText(1, _translate("FormLoadsCreator", "Расчетные длительные"))
        self.comboBoxLoadsType.setItemText(2, _translate("FormLoadsCreator", "Нормативные"))
        self.comboBoxLoadsType.setItemText(3, _translate("FormLoadsCreator", "Нормативные длительные"))
        self.label_8.setText(_translate("FormLoadsCreator", "Доля длительности нагрузки*"))
        self.label_4.setText(_translate("FormLoadsCreator", "Коэффициент надежности по нагрузке"))
        self.label_3.setText(_translate("FormLoadsCreator", "N, кН"))
        self.label_2.setText(_translate("FormLoadsCreator", "Mx, кНм"))
        self.label.setText(_translate("FormLoadsCreator", "My, кНм"))
        self.pushButtonAddLoad.setText(_translate("FormLoadsCreator", "Добавить усилие"))
        self.pushButtonEditLoad.setText(_translate("FormLoadsCreator", "Изменить усилие"))
        self.pushButtonDelLoad.setText(_translate("FormLoadsCreator", "Удалить усилие"))
        self.label_6.setText(_translate("FormLoadsCreator", "Преобразовать в:"))
        self.comboBoxTypeConversion.setItemText(0, _translate("FormLoadsCreator", "Расчетные"))
        self.comboBoxTypeConversion.setItemText(1, _translate("FormLoadsCreator", "Расчетные длительные"))
        self.comboBoxTypeConversion.setItemText(2, _translate("FormLoadsCreator", "Нормативные"))
        self.comboBoxTypeConversion.setItemText(3, _translate("FormLoadsCreator", "Нормативные длительные"))
        self.pushButtonDelLodsGroup.setText(_translate("FormLoadsCreator", "Удалить группу"))
