# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\YandexDisk\Документы\Python Scripts\NDM_python\designer\formMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainVLayout = QtWidgets.QVBoxLayout()
        self.mainVLayout.setObjectName("mainVLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageStart = QtWidgets.QWidget()
        self.pageStart.setObjectName("pageStart")
        self.stackedWidget.addWidget(self.pageStart)
        self.pageMaterials = QtWidgets.QWidget()
        self.pageMaterials.setObjectName("pageMaterials")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageMaterials)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBoxBeton = QtWidgets.QGroupBox(self.pageMaterials)
        self.groupBoxBeton.setObjectName("groupBoxBeton")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBoxBeton)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableViewBeton = QtWidgets.QTableView(self.groupBoxBeton)
        self.tableViewBeton.setObjectName("tableViewBeton")
        self.verticalLayout_6.addWidget(self.tableViewBeton)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addWidget(self.groupBoxBeton)
        self.groupBoxArm = QtWidgets.QGroupBox(self.pageMaterials)
        self.groupBoxArm.setObjectName("groupBoxArm")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBoxArm)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableViewArm = QtWidgets.QTableView(self.groupBoxArm)
        self.tableViewArm.setObjectName("tableViewArm")
        self.verticalLayout_7.addWidget(self.tableViewArm)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_4.addWidget(self.groupBoxArm)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.stackedWidget.addWidget(self.pageMaterials)
        self.pageLoads = QtWidgets.QWidget()
        self.pageLoads.setObjectName("pageLoads")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.pageLoads)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.toolBoxLoads = QtWidgets.QToolBox(self.pageLoads)
        self.toolBoxLoads.setObjectName("toolBoxLoads")
        self.pageC = QtWidgets.QWidget()
        self.pageC.setGeometry(QtCore.QRect(0, 0, 762, 397))
        self.pageC.setObjectName("pageC")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.pageC)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.tableViewC = QtWidgets.QTableView(self.pageC)
        self.tableViewC.setObjectName("tableViewC")
        self.verticalLayout_22.addWidget(self.tableViewC)
        self.verticalLayout_27.addLayout(self.verticalLayout_22)
        self.toolBoxLoads.addItem(self.pageC, "")
        self.pageCL = QtWidgets.QWidget()
        self.pageCL.setGeometry(QtCore.QRect(0, 0, 98, 91))
        self.pageCL.setObjectName("pageCL")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.pageCL)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.tableViewCL = QtWidgets.QTableView(self.pageCL)
        self.tableViewCL.setObjectName("tableViewCL")
        self.verticalLayout_24.addWidget(self.tableViewCL)
        self.verticalLayout_28.addLayout(self.verticalLayout_24)
        self.toolBoxLoads.addItem(self.pageCL, "")
        self.pageN = QtWidgets.QWidget()
        self.pageN.setGeometry(QtCore.QRect(0, 0, 98, 91))
        self.pageN.setObjectName("pageN")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.pageN)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.tableViewN = QtWidgets.QTableView(self.pageN)
        self.tableViewN.setObjectName("tableViewN")
        self.verticalLayout_25.addWidget(self.tableViewN)
        self.verticalLayout_29.addLayout(self.verticalLayout_25)
        self.toolBoxLoads.addItem(self.pageN, "")
        self.pageNL = QtWidgets.QWidget()
        self.pageNL.setGeometry(QtCore.QRect(0, 0, 762, 397))
        self.pageNL.setObjectName("pageNL")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.pageNL)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.tableViewNL = QtWidgets.QTableView(self.pageNL)
        self.tableViewNL.setObjectName("tableViewNL")
        self.verticalLayout_26.addWidget(self.tableViewNL)
        self.verticalLayout_30.addLayout(self.verticalLayout_26)
        self.toolBoxLoads.addItem(self.pageNL, "")
        self.verticalLayout_23.addWidget(self.toolBoxLoads)
        self.stackedWidget.addWidget(self.pageLoads)
        self.pageContoursTable = QtWidgets.QWidget()
        self.pageContoursTable.setObjectName("pageContoursTable")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.pageContoursTable)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableViewContour = QtWidgets.QTableView(self.pageContoursTable)
        self.tableViewContour.setObjectName("tableViewContour")
        self.horizontalLayout_2.addWidget(self.tableViewContour)
        self.graphicsViewContour = QtWidgets.QGraphicsView(self.pageContoursTable)
        self.graphicsViewContour.setObjectName("graphicsViewContour")
        self.horizontalLayout_2.addWidget(self.graphicsViewContour)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.verticalLayout_18.addLayout(self.verticalLayout_13)
        self.stackedWidget.addWidget(self.pageContoursTable)
        self.pageArmInstallsTable = QtWidgets.QWidget()
        self.pageArmInstallsTable.setObjectName("pageArmInstallsTable")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.pageArmInstallsTable)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableViewArmInstall = QtWidgets.QTableView(self.pageArmInstallsTable)
        self.tableViewArmInstall.setObjectName("tableViewArmInstall")
        self.horizontalLayout_3.addWidget(self.tableViewArmInstall)
        self.graphicsViewArmInstall = QtWidgets.QGraphicsView(self.pageArmInstallsTable)
        self.graphicsViewArmInstall.setObjectName("graphicsViewArmInstall")
        self.horizontalLayout_3.addWidget(self.graphicsViewArmInstall)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)
        self.verticalLayout_19.addLayout(self.verticalLayout_14)
        self.stackedWidget.addWidget(self.pageArmInstallsTable)
        self.pageNodesTable = QtWidgets.QWidget()
        self.pageNodesTable.setObjectName("pageNodesTable")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageNodesTable)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableViewNodes = QtWidgets.QTableView(self.pageNodesTable)
        self.tableViewNodes.setObjectName("tableViewNodes")
        self.verticalLayout.addWidget(self.tableViewNodes)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.stackedWidget.addWidget(self.pageNodesTable)
        self.pageFesTable = QtWidgets.QWidget()
        self.pageFesTable.setObjectName("pageFesTable")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pageFesTable)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableViewFes = QtWidgets.QTableView(self.pageFesTable)
        self.tableViewFes.setObjectName("tableViewFes")
        self.verticalLayout_10.addWidget(self.tableViewFes)
        self.verticalLayout_15.addLayout(self.verticalLayout_10)
        self.stackedWidget.addWidget(self.pageFesTable)
        self.pageElementsTable = QtWidgets.QWidget()
        self.pageElementsTable.setObjectName("pageElementsTable")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.pageElementsTable)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tableViewElements = QtWidgets.QTableView(self.pageElementsTable)
        self.tableViewElements.setObjectName("tableViewElements")
        self.verticalLayout_11.addWidget(self.tableViewElements)
        self.verticalLayout_16.addLayout(self.verticalLayout_11)
        self.stackedWidget.addWidget(self.pageElementsTable)
        self.pageSections = QtWidgets.QWidget()
        self.pageSections.setObjectName("pageSections")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.pageSections)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.tableViewSections = QtWidgets.QTableView(self.pageSections)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewSections.sizePolicy().hasHeightForWidth())
        self.tableViewSections.setSizePolicy(sizePolicy)
        self.tableViewSections.setObjectName("tableViewSections")
        self.verticalLayout_21.addWidget(self.tableViewSections)
        self.horizontalLayout.addLayout(self.verticalLayout_21)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.graphicsViewSection = QtWidgets.QGraphicsView(self.pageSections)
        self.graphicsViewSection.setObjectName("graphicsViewSection")
        self.verticalLayout_20.addWidget(self.graphicsViewSection)
        self.horizontalLayout.addLayout(self.verticalLayout_20)
        self.verticalLayout_12.addLayout(self.horizontalLayout)
        self.verticalLayout_17.addLayout(self.verticalLayout_12)
        self.stackedWidget.addWidget(self.pageSections)
        self.mainVLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addLayout(self.mainVLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAdd = QtWidgets.QMenu(self.menubar)
        self.menuAdd.setObjectName("menuAdd")
        self.menuAddLoads = QtWidgets.QMenu(self.menuAdd)
        self.menuAddLoads.setObjectName("menuAddLoads")
        self.menuAddSection = QtWidgets.QMenu(self.menuAdd)
        self.menuAddSection.setObjectName("menuAddSection")
        self.menuAddContour = QtWidgets.QMenu(self.menuAddSection)
        self.menuAddContour.setObjectName("menuAddContour")
        self.menuAddArmInstallation = QtWidgets.QMenu(self.menuAddSection)
        self.menuAddArmInstallation.setObjectName("menuAddArmInstallation")
        self.menuAddMaterials = QtWidgets.QMenu(self.menuAdd)
        self.menuAddMaterials.setObjectName("menuAddMaterials")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuViewTables = QtWidgets.QMenu(self.menuView)
        self.menuViewTables.setObjectName("menuViewTables")
        self.menuCalculation = QtWidgets.QMenu(self.menubar)
        self.menuCalculation.setObjectName("menuCalculation")
        self.menuResults = QtWidgets.QMenu(self.menubar)
        self.menuResults.setObjectName("menuResults")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuDXF = QtWidgets.QMenu(self.menuImport)
        self.menuDXF.setObjectName("menuDXF")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionAddFe = QtWidgets.QAction(MainWindow)
        self.actionAddFe.setObjectName("actionAddFe")
        self.actionAddElement = QtWidgets.QAction(MainWindow)
        self.actionAddElement.setObjectName("actionAddElement")
        self.actionAddLoadsC = QtWidgets.QAction(MainWindow)
        self.actionAddLoadsC.setObjectName("actionAddLoadsC")
        self.actionAddLoadsCL = QtWidgets.QAction(MainWindow)
        self.actionAddLoadsCL.setObjectName("actionAddLoadsCL")
        self.actionAddLoadsN = QtWidgets.QAction(MainWindow)
        self.actionAddLoadsN.setObjectName("actionAddLoadsN")
        self.actionAddLoadsNL = QtWidgets.QAction(MainWindow)
        self.actionAddLoadsNL.setObjectName("actionAddLoadsNL")
        self.actionViewTableNodes = QtWidgets.QAction(MainWindow)
        self.actionViewTableNodes.setObjectName("actionViewTableNodes")
        self.actionViewTableFes = QtWidgets.QAction(MainWindow)
        self.actionViewTableFes.setObjectName("actionViewTableFes")
        self.actionViewTableSections = QtWidgets.QAction(MainWindow)
        self.actionViewTableSections.setObjectName("actionViewTableSections")
        self.actionViewTableLoads = QtWidgets.QAction(MainWindow)
        self.actionViewTableLoads.setObjectName("actionViewTableLoads")
        self.actionViewTableElements = QtWidgets.QAction(MainWindow)
        self.actionViewTableElements.setObjectName("actionViewTableElements")
        self.actionAddNode = QtWidgets.QAction(MainWindow)
        self.actionAddNode.setObjectName("actionAddNode")
        self.actionEditSections = QtWidgets.QAction(MainWindow)
        self.actionEditSections.setObjectName("actionEditSections")
        self.actionEditNodes = QtWidgets.QAction(MainWindow)
        self.actionEditNodes.setObjectName("actionEditNodes")
        self.actionAddBeton = QtWidgets.QAction(MainWindow)
        self.actionAddBeton.setObjectName("actionAddBeton")
        self.actionAddArm = QtWidgets.QAction(MainWindow)
        self.actionAddArm.setObjectName("actionAddArm")
        self.actionEditBeton = QtWidgets.QAction(MainWindow)
        self.actionEditBeton.setObjectName("actionEditBeton")
        self.actionEditArm = QtWidgets.QAction(MainWindow)
        self.actionEditArm.setObjectName("actionEditArm")
        self.actionEditFes = QtWidgets.QAction(MainWindow)
        self.actionEditFes.setObjectName("actionEditFes")
        self.actionEditElements = QtWidgets.QAction(MainWindow)
        self.actionEditElements.setObjectName("actionEditElements")
        self.actionEditLoadsC = QtWidgets.QAction(MainWindow)
        self.actionEditLoadsC.setObjectName("actionEditLoadsC")
        self.actionEditLoadsCL = QtWidgets.QAction(MainWindow)
        self.actionEditLoadsCL.setObjectName("actionEditLoadsCL")
        self.actionEditLoadsN = QtWidgets.QAction(MainWindow)
        self.actionEditLoadsN.setObjectName("actionEditLoadsN")
        self.actionEditLoadsNL = QtWidgets.QAction(MainWindow)
        self.actionEditLoadsNL.setObjectName("actionEditLoadsNL")
        self.actionViewTableMaterials = QtWidgets.QAction(MainWindow)
        self.actionViewTableMaterials.setObjectName("actionViewTableMaterials")
        self.actionViewSections = QtWidgets.QAction(MainWindow)
        self.actionViewSections.setObjectName("actionViewSections")
        self.actionViewResults = QtWidgets.QAction(MainWindow)
        self.actionViewResults.setObjectName("actionViewResults")
        self.actionAddContourRect = QtWidgets.QAction(MainWindow)
        self.actionAddContourRect.setObjectName("actionAddContourRect")
        self.actionAddContourCircle = QtWidgets.QAction(MainWindow)
        self.actionAddContourCircle.setObjectName("actionAddContourCircle")
        self.actionAddContourTavr = QtWidgets.QAction(MainWindow)
        self.actionAddContourTavr.setObjectName("actionAddContourTavr")
        self.actionAddContourDvtavr = QtWidgets.QAction(MainWindow)
        self.actionAddContourDvtavr.setObjectName("actionAddContourDvtavr")
        self.actionAddContourRing = QtWidgets.QAction(MainWindow)
        self.actionAddContourRing.setObjectName("actionAddContourRing")
        self.actionAddContourRectTube = QtWidgets.QAction(MainWindow)
        self.actionAddContourRectTube.setObjectName("actionAddContourRectTube")
        self.actionAddContourUser = QtWidgets.QAction(MainWindow)
        self.actionAddContourUser.setObjectName("actionAddContourUser")
        self.actionAddArmInstallation3x3 = QtWidgets.QAction(MainWindow)
        self.actionAddArmInstallation3x3.setObjectName("actionAddArmInstallation3x3")
        self.actionAddArmInstallationUnit = QtWidgets.QAction(MainWindow)
        self.actionAddArmInstallationUnit.setObjectName("actionAddArmInstallationUnit")
        self.actionAddSection = QtWidgets.QAction(MainWindow)
        self.actionAddSection.setObjectName("actionAddSection")
        self.actionDXFContour = QtWidgets.QAction(MainWindow)
        self.actionDXFContour.setObjectName("actionDXFContour")
        self.actionArmInstall = QtWidgets.QAction(MainWindow)
        self.actionArmInstall.setObjectName("actionArmInstall")
        self.actionSection = QtWidgets.QAction(MainWindow)
        self.actionSection.setObjectName("actionSection")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionCrackResist = QtWidgets.QAction(MainWindow)
        self.actionCrackResist.setObjectName("actionCrackResist")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuAddLoads.addAction(self.actionAddLoadsC)
        self.menuAddLoads.addAction(self.actionAddLoadsCL)
        self.menuAddLoads.addAction(self.actionAddLoadsN)
        self.menuAddLoads.addAction(self.actionAddLoadsNL)
        self.menuAddContour.addAction(self.actionAddContourRect)
        self.menuAddContour.addAction(self.actionAddContourCircle)
        self.menuAddContour.addAction(self.actionAddContourTavr)
        self.menuAddContour.addAction(self.actionAddContourDvtavr)
        self.menuAddContour.addAction(self.actionAddContourRing)
        self.menuAddContour.addAction(self.actionAddContourRectTube)
        self.menuAddContour.addAction(self.actionAddContourUser)
        self.menuAddArmInstallation.addAction(self.actionAddArmInstallation3x3)
        self.menuAddArmInstallation.addAction(self.actionAddArmInstallationUnit)
        self.menuAddSection.addAction(self.menuAddContour.menuAction())
        self.menuAddSection.addAction(self.menuAddArmInstallation.menuAction())
        self.menuAddSection.addAction(self.actionAddSection)
        self.menuAddMaterials.addAction(self.actionAddBeton)
        self.menuAddMaterials.addAction(self.actionAddArm)
        self.menuAdd.addAction(self.menuAddMaterials.menuAction())
        self.menuAdd.addAction(self.menuAddLoads.menuAction())
        self.menuAdd.addAction(self.menuAddSection.menuAction())
        self.menuAdd.addAction(self.actionAddNode)
        self.menuAdd.addAction(self.actionAddFe)
        self.menuAdd.addAction(self.actionAddElement)
        self.menuAdd.addAction(self.actionCrackResist)
        self.menuViewTables.addAction(self.actionViewTableMaterials)
        self.menuViewTables.addAction(self.actionViewTableNodes)
        self.menuViewTables.addAction(self.actionViewTableLoads)
        self.menuViewTables.addAction(self.actionViewTableSections)
        self.menuViewTables.addAction(self.actionViewTableFes)
        self.menuViewTables.addAction(self.actionViewTableElements)
        self.menuView.addAction(self.menuViewTables.menuAction())
        self.menuView.addAction(self.actionViewSections)
        self.menuView.addAction(self.actionViewResults)
        self.menuDXF.addAction(self.actionDXFContour)
        self.menuDXF.addAction(self.actionArmInstall)
        self.menuDXF.addAction(self.actionSection)
        self.menuImport.addAction(self.menuDXF.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAdd.menuAction())
        self.menubar.addAction(self.menuCalculation.menuAction())
        self.menubar.addAction(self.menuResults.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBoxLoads.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Бетон НДМ"))
        self.groupBoxBeton.setTitle(_translate("MainWindow", "Бетон"))
        self.groupBoxArm.setTitle(_translate("MainWindow", "Арматура"))
        self.toolBoxLoads.setItemText(self.toolBoxLoads.indexOf(self.pageC), _translate("MainWindow", "Расчетные"))
        self.toolBoxLoads.setItemText(self.toolBoxLoads.indexOf(self.pageCL), _translate("MainWindow", "Расчетные длительные"))
        self.toolBoxLoads.setItemText(self.toolBoxLoads.indexOf(self.pageN), _translate("MainWindow", "Нормативные"))
        self.toolBoxLoads.setItemText(self.toolBoxLoads.indexOf(self.pageNL), _translate("MainWindow", "Нормативные длительные"))
        self.menuFile.setTitle(_translate("MainWindow", "&Файл"))
        self.menuAdd.setTitle(_translate("MainWindow", "Исходные данные"))
        self.menuAddLoads.setTitle(_translate("MainWindow", "Усилия"))
        self.menuAddSection.setTitle(_translate("MainWindow", "Сечения"))
        self.menuAddContour.setTitle(_translate("MainWindow", "Контур"))
        self.menuAddArmInstallation.setTitle(_translate("MainWindow", "Армирование"))
        self.menuAddMaterials.setTitle(_translate("MainWindow", "Материалы"))
        self.menuView.setTitle(_translate("MainWindow", "Вид"))
        self.menuViewTables.setTitle(_translate("MainWindow", "Таблицы"))
        self.menuCalculation.setTitle(_translate("MainWindow", "Расчет"))
        self.menuResults.setTitle(_translate("MainWindow", "Результаты"))
        self.menuHelp.setTitle(_translate("MainWindow", "Помощь"))
        self.menuImport.setTitle(_translate("MainWindow", "Импорт"))
        self.menuDXF.setTitle(_translate("MainWindow", "DXF"))
        self.actionNew.setText(_translate("MainWindow", "Новый"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить"))
        self.actionSaveAs.setText(_translate("MainWindow", "Сохранить как"))
        self.actionExport.setText(_translate("MainWindow", "Экспорт"))
        self.actionSettings.setText(_translate("MainWindow", "Параметры"))
        self.actionQuit.setText(_translate("MainWindow", "Выход"))
        self.action_2.setText(_translate("MainWindow", "Арматура"))
        self.actionAddFe.setText(_translate("MainWindow", "Участки"))
        self.actionAddElement.setText(_translate("MainWindow", "Элементы"))
        self.actionAddLoadsC.setText(_translate("MainWindow", "Расчетные"))
        self.actionAddLoadsCL.setText(_translate("MainWindow", "Расчетные длительные"))
        self.actionAddLoadsN.setText(_translate("MainWindow", "Нормативные"))
        self.actionAddLoadsNL.setText(_translate("MainWindow", "Нормативные длительные"))
        self.actionViewTableNodes.setText(_translate("MainWindow", "Узлы"))
        self.actionViewTableFes.setText(_translate("MainWindow", "Участки"))
        self.actionViewTableSections.setText(_translate("MainWindow", "Сечения"))
        self.actionViewTableLoads.setText(_translate("MainWindow", "Усилия"))
        self.actionViewTableElements.setText(_translate("MainWindow", "Элементы"))
        self.actionAddNode.setText(_translate("MainWindow", "Узлы"))
        self.actionEditSections.setText(_translate("MainWindow", "Сечения"))
        self.actionEditNodes.setText(_translate("MainWindow", "Узел"))
        self.actionAddBeton.setText(_translate("MainWindow", "Бетон"))
        self.actionAddArm.setText(_translate("MainWindow", "Арматура"))
        self.actionEditBeton.setText(_translate("MainWindow", "Бетон"))
        self.actionEditArm.setText(_translate("MainWindow", "Арматура"))
        self.actionEditFes.setText(_translate("MainWindow", "Участок"))
        self.actionEditElements.setText(_translate("MainWindow", "Элемент"))
        self.actionEditLoadsC.setText(_translate("MainWindow", "Расчетные"))
        self.actionEditLoadsCL.setText(_translate("MainWindow", "Расчетные длительные"))
        self.actionEditLoadsN.setText(_translate("MainWindow", "Нормативные"))
        self.actionEditLoadsNL.setText(_translate("MainWindow", "Нормативные длительные"))
        self.actionViewTableMaterials.setText(_translate("MainWindow", "Материалы"))
        self.actionViewSections.setText(_translate("MainWindow", "Сечения"))
        self.actionViewResults.setText(_translate("MainWindow", "Результаты"))
        self.actionAddContourRect.setText(_translate("MainWindow", "Прямоугольник"))
        self.actionAddContourCircle.setText(_translate("MainWindow", "Круг"))
        self.actionAddContourTavr.setText(_translate("MainWindow", "Тавр"))
        self.actionAddContourDvtavr.setText(_translate("MainWindow", "Двутавр"))
        self.actionAddContourRing.setText(_translate("MainWindow", "Кольцо"))
        self.actionAddContourRectTube.setText(_translate("MainWindow", "Полый прямоугольник"))
        self.actionAddContourUser.setText(_translate("MainWindow", "Произвольный"))
        self.actionAddArmInstallation3x3.setText(_translate("MainWindow", "3 x 3 расстановка"))
        self.actionAddArmInstallationUnit.setText(_translate("MainWindow", "Одиночная установка"))
        self.actionAddSection.setText(_translate("MainWindow", "Сечение"))
        self.actionDXFContour.setText(_translate("MainWindow", "Контур"))
        self.actionArmInstall.setText(_translate("MainWindow", "Армирование"))
        self.actionSection.setText(_translate("MainWindow", "Сечение"))
        self.actionOpen.setText(_translate("MainWindow", "Открыть"))
        self.actionCrackResist.setText(_translate("MainWindow", "Трещиностойкость"))
